const CONFIG = {
  APP_NAME: 'Keuangan UMKM',

  SHEETS: {
    USERS: 'USERS',
    TX: 'TRANSACTIONS',
    TX_BENGKEL: 'TX_BENGKEL',
    TX_CUCIAN: 'TX_CUCIAN',
    LOG: 'ACTIVITY_LOG',
    SETTINGS: 'SETTINGS',
  },

  PAGE_SIZE: 10,
  UMKM: ['BENGKEL', 'CUCIAN'],
  PAYMENT: ['CASH', 'TRANSFER'],
  TYPE: ['PEMASUKAN', 'PENGELUARAN'],

  // SETTINGS keys
  ADMIN_KEY_HASH: 'ADMIN_KEY_HASH',
  REPORT_FOLDER_ID: 'REPORT_FOLDER_ID',

  REPORT_FOLDER_NAME: 'Keuangan UMKM - Laporan',

  // session
  SESSION_TTL_MINUTES: 60 * 12, // 12 jam
};
